BoundPyOpenCLProgram: do not store a queue
inducer/pytato pull request #48
Opened 2021-03-12 04:11 UTC by inducer

2021-03-12 19:13 UTC, kaushikcfd requested changes
I have one concern on which many other proposed changes depend.

2021-03-12 19:13 UTC, kaushikcfd commented on pytato/target/loopy/codegen.py
> +        cl_device: Optional["pyopencl.Device"] = None) -> BoundProgram:
cl_device should be passed via target. Passing cl_device to generate_loopy makes generate_loopy CL-specific which it shouldn't be.

2021-03-13 00:26 UTC, inducer commented on pytato/target/loopy/codegen.py
> +        cl_device: Optional["pyopencl.Device"] = None) -> BoundProgram:
I see what you're saying, but I don't quite see it that way. The new interface isn't any less general than the one before this change: You can still pass `target` and use any target you like. Passing `cl_device` is just a shorthand for "use the CL target with this device", to win a few characters in a very frequently used function. (dabbea5 makes it explicit that you should either pass one or the other, but never both, and c52e205 makes `cl_device` kw-only).

2021-03-13 00:27 UTC, inducer commented on pytato/target/loopy/codegen.py
> +        cl_device: Optional["pyopencl.Device"] = None) -> BoundProgram:
Do you find that acceptable, or would you prefer the explicit target still?

2021-03-13 02:00 UTC, kaushikcfd approved these changes
LGTM. One minor concern, that's also optional for the merge. Thanks!

2021-03-13 21:40 UTC, inducer commented on pytato/target/__init__.py
> -    def __call__(self, *args: Any, **kwargs: Any) -> Any:
It is, but I feel that the interface will vary based on the subclass. (PyOpenCL needing a `queue` for example.) And mypy was unhappy about that, so the easiest way around that as to remove the interface from the base class. Got a better idea?

Bonus formatting tip:
```
`__call__` vs __call__
```
`__call__` vs __call__

2021-03-14 00:01 UTC, kaushikcfd commented on pytato/target/__init__.py
> -    def __call__(self, *args: Any, **kwargs: Any) -> Any:
Yep, reasonable. Can't seem to find anything better.

2021-03-14 00:23 UTC, inducer commented on pytato/target/__init__.py
> -    def __call__(self, *args: Any, **kwargs: Any) -> Any:
35b6a4c adds docs to clarify.

2021-03-14 00:24 UTC, inducer commented
@kaushikcfd Thanks for taking a look!

2021-03-14 00:28 UTC, merged